version: '3'

services:

  inpress:
    image: inpress/task:v1
    ports:
      - "8080:8080"
    depends_on:
      - grafana

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus



volumes:
  elasticsearch_data:
    driver: local
